Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Franklyn Dias dos Santos
// Data atual  : 13/05/2024
Var
// Seção de Declarações das variáveis 
msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval ("Ola, Mundo!")
  Escreva ("Me livrei da maldicao!")

Fimalgoritmo