Algoritmo "NotaAlunoMedia"

Var
// Seção de Declarações das variáveis 
 N1, N2, M: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Escola Javali Cansado")
Escreva ("Primeira Nota ")
Leia (N1)
Escreva ("Segunda Nota ")
Leia (N2)
M <- (N1 + N2) /2
Escreval ("A media do aluno foi ", M:4:2)
Se (m >= 7) entao
Escreval ("Aluno Aprovado")
Senao
Escreval ("Aluno Reprovado")
FimSe
Fimalgoritmo