Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
valor, contador : Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     contador <- 0
     Escreva ("Quer contar até quanto? ")
     Leia (valor)
     Enquanto (contador <= valor) faça
              Escreval(contador)
              contador <- contador + 1
FimEnquanto
Escreval ("Terminei de contar")
Fimalgoritmo