Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2024
Var
// Seção de Declarações das variáveis 
     Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreva ("Digite seu nome: ")
     Leia (Nome)
     Escreva ("Muito prazer ", Nome)
Fimalgoritmo
